# Generated by Django 6.1 on 2026-08-27 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonebookAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='phonebook.phonebookxml')),
            ],
            options={
                'ordering': ('-accessed_at',),
                'indexes': [models.Index(fields=['phonebook', '-accessed_at'], name='phonebook_p_phonebo_b22717_idx')],
            },
        ),
    ]
